CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    request_id TEXT NOT NULL,
    correlation_id TEXT,
    user_id TEXT NOT NULL,
    session_id TEXT,
    api_key_id TEXT,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    query_params TEXT,
    resource TEXT NOT NULL,
    action TEXT NOT NULL,
    api_version TEXT,
    ip_address TEXT,
    real_ip TEXT,
    forwarded_for TEXT,
    port INTEGER NOT NULL DEFAULT 0,
    protocol TEXT NOT NULL DEFAULT '',
    user_agent TEXT,
    client_version TEXT,
    accept_language TEXT,
    accept_encoding TEXT,
    referer TEXT,
    origin TEXT,
    fingerprint TEXT,
    device_fingerprint TEXT,
    tls_fingerprint TEXT,
    request_size INTEGER NOT NULL DEFAULT 0,
    response_size INTEGER,
    response_time_ms INTEGER,
    response_status INTEGER,
    geo_info TEXT,
    security_signals TEXT,
    request_headers TEXT,
    response_headers TEXT,
    request_body_sample TEXT,
    response_body_sample TEXT,
    error_message TEXT,
    error_type TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_path ON audit_logs(path);